export default {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_HOMEFEED: 'FETCH_HOMEFEED',
    FETCH_GLOBALFEED: 'FETCH_GLOBALFEED',
    FETCH_USERFEED: 'FETCH_USERFEED',
    SEARCH_GLOBALFEED: 'SEARCH_GLOBALFEED',
    SEARCH_USERS: 'SEARCH_USERS',
    FETCH_USER: 'FETCH_USER',
    SET_GRAB_TYPE: 'SET_GRAB_TYPE',
    SET_STAGE_SELECT: 'SET_STAGE_SELECT',
    SET_IMAGE: 'SET_IMAGE',
    UPLOAD_FILE: "UPLOAD_FILE",
    RESIZE_IMAGE: 'RESIZE_IMAGE'
}