export default {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_HOMEFEED: 'FETCH_HOMEFEED',
    FETCH_GLOBALFEED: 'FETCH_GLOBALFEED',
    SEARCH_GLOBALFEED: 'SEARCH_GLOBALFEED',
    SEARCH_USERS: 'SEARCH_USERS',
    FETCH_USER: 'FETCH_USER',
    FETCH_COMMENTS: 'FETCH_COMMENTS',
    POST_POST: 'POST_POST',
    POST_COMMENT: 'POST_COMMENT'
}